### ISSUE TITLE
[Guía] Objetivos para la versión v0.1.0

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/EventPoints#1]
# v0.1.0

### Objetivo

En esta primera release tenemos como objetivo definir y crear un versión mínima del proyecto.

### Detalles

**Limitaciones:**

- Solo incluiremos eventos de Madrid (ciudad).
- Solo eventos de la próxima semana.
- El contenido de la base de datos se generará una vez por semana (Domingo)

**Objetivos Principales:**

- Encontrar/decidir un nombre para el proyectos
- Todo automatizado (cero trabajo manual, cero mantenimiento)
- Agregar fuentes de datos:
    - Campus Madrid
    - Media Lab Prado
    - Eventbrite
- Disposición de la información:
    - Front (HTML, CSS..)
    - Api básica (JSON)

**Objetivos Secundarios:**

- Agregar fuentes de datos:
    - Betabeers
- Disposición de la información:
    - RSS
    - Exportación calendarios (Apple, Google, etc...)

**Comment by rgarciaduarte** [comment]
@UlisesGascon vamos a cerrar tareas y a crear nuevas, si tienes cualquier comentario dime ;)
