### ISSUE TITLE
Tareas Front pendientes

### ISSUE THREAD

**Issue by Borjagodoy** [OSWeekends/EventPoints#16]
Las siguientes tareas son necesarias en el Front con Polymer.

- [ ] Añadir iconos

- [x] Ajustar CSS en la vista detalle

- [ ] Añadir local storage para cachear los datos de cada página

- [ ] Arreglar bug con el marker en Google Maps

- [ ] Añadir fuente

- [ ] Mejorar la UX en la visualización de la fecha de los eventos, al estar agrupadas debe de ser distinta a la diseñada.

- [ ] Ajusstar CSS en botones del detalle

- [ ] Deshabilitar cache

**Comment by LeylaVieira** [comment]
Hi a todos! para mejorar la visualización, propongo agrupar los eventos por fechas:

![ui-eventpoints-mobile-screen1](https://cloud.githubusercontent.com/assets/24264883/22551950/370c008e-e957-11e6-9421-5992b63b5cb0.png)

Y siguiendo lo que está implementado, la interacción sería:

![ui-eventpoints-mobile-v3](https://cloud.githubusercontent.com/assets/24264883/22552079/ae56e348-e957-11e6-88db-484a2dbbafdf.gif)
