### ISSUE TITLE
[Guía] Como colaborar...

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/EventPoints#2]
Hola a todos!

El proyecto esta abierto a todos... nos estamos organizando entre este repositorio y el canal de **proyecto-calendario** en Slack. 

Puedes unirte a Slack desde [este enlace](https://invitations-osweekends.herokuapp.com/).

Estamos buscando sobretodo equipo en el front (CSS, HTML, JS (Ajax)), para esta versión el trabajo del front será muy ligero. 

Si alguien se anima a desarrollar el front sin frameworks no hay problema, si no... optaremos por el clásico [Bootstrap Material](http://fezvrasta.github.io/bootstrap-material-design/) como en el [proyecto Curratelo](http://curratelo.herokuapp.com/)

En el back estamos trabajando con Python, Node y Firebase. También estaría genial contar con algo más de ayuda... sobretodo para tareas de automatización con Gulp o en desarrollo en general...

### Equipo
Por el momento el equipo esta compuesto por:

- @Josheriff (Backend)
- @UlisesGascon (Backend)
- @IgnaciodeNuevo (Frontend)
- @carquet (Backend y Frontend)
- @xDae (Frontend)
- @sergormo (diseño)
- @LeylaVieira (diseño)
- @Borjagodoy (Frontend)
- **¿Te sumas?**

### Trabajo en Ramas

- Todo en la rama [dev](https://github.com/OSWeekends/calendario/tree/dev)

### Importante

Queremos tener la versión v0.1.0 lista para la [reunión de Enero](https://www.meetup.com/es-ES/Open-Source-Weekends/events/236190563/) (14/01/17).

**Comment by IgnaciodeNuevo** [comment]
NADA de Bootstrap, front here to rock

**Comment by UlisesGascon** [comment]
Pues te añado @IgnaciodeNuevo !

**Comment by carquet** [comment]
yo estoy interesada en front y back......Es que todavía me siento full.

**Comment by UlisesGascon** [comment]
Bienvenida @carquet! Te añado...

**Comment by UlisesGascon** [comment]
Añadidos @xDae (Frontend), @sergormo (diseño) y @LeylaVieira (diseño)

**Comment by Borjagodoy** [comment]
Cuenta con mi hacha @UlisesGascon  en Front evidentemente y sabes lo que intentaré meter :)

**Comment by UlisesGascon** [comment]
@Borjagodoy ya te añado! 👍

**Comment by rgarciaduarte** [comment]
Hey, vamos <a cerrar issues antiguas para eliminar algo de ruido de las issues, si tenéis cualquier duda, comentarme.
