### ISSUE TITLE
[Guía] Arquitectura Front y Back

### ISSUE THREAD

**Issue by UlisesGascon** [OSWeekends/EventPoints#3]
**Estado:** Borrador

### Front

- El front será totalmente independiente del back
- Se nutrirá de la API (/api/eventos) o Firebase
- Los eventos ya vendrán limpios desde el back o Firebase y con un formato muy definido.
- Creamos los estilos desde cero o usaremos [Bootstrap Material](http://fezvrasta.github.io/bootstrap-material-design/) como en el [proyecto Curratelo](http://curratelo.herokuapp.com/)
- No usaremos frameworks JavaScript en un principio... aunque todo es negociable 😄 

### Back

- Las fuentes de datos puedes ser RSS o directamente generadas desde un proceso de scrapeo.
- Para gestionar la parte de HTTP y los procesos hijo... utilizaremos Node.js
- Para gestionar el scraping utilizaremos Python y [Beautiful Soup](https://es.wikipedia.org/wiki/Beautiful_Soup)
- Utilizaremos Gulp para gestionar la automatización de tareas
- Firebase será la base de datos que utilizaremos
- Utilizaremos [Pillars.js](http://pillarsjs.com/) para gestionar el servidor HTTP.
- Utilizaremos [scheduled](https://github.com/pillarsjs/scheduled) para gestionar las tareas CRON de scrapeo.
- Será necesario cerrar un formato común para todos los eventos.
- Es necesario gestionar la duplicación de eventos.. utilizando criterios comunes como la URL final

**Comment by Borjagodoy** [comment]
Yo como yha te dije Ulises creo que podríamos usar web components, Polymer is not a Framework!!

**Comment by UlisesGascon** [comment]
@Borjagodoy... Ni polymer, ni vieja escuela... @xDae se animó con React... y en eso estamos :)

Pasate por el canal de Slack (proyecto-eventpoints) y te ponemos al día

**Comment by IgnaciodeNuevo** [comment]
¿Polymer? Nein. Hemos quedado @xDae y yo que React :)
