### ISSUE TITLE
Ideas y testeos para logo, branding, y color codes.

### ISSUE THREAD

**Issue by sergormo** [OSWeekends/EventPoints#8]
No se quien dijo rosa, pero que cojones!, se puede hacer rosa con clase.
Así en plan rápido, la idea es jugar con colores en rango desde

triadas y degradados:
#c62026 -- #ee2362 -- white

**Comment by Josheriff** [comment]
Lo que mas te divierta, recuerda que no está hecho para ganar dinero, ni branding ni leches,PASATELO BIEN. 

Un abrazo

**Comment by sergormo** [comment]
![Logo7]
(https://www.dropbox.com/s/l8dihviot5g9ht1/triadas.png)

![Logo1]
(https://www.dropbox.com/s/z93yir0srq7amh5/Artboard%2011%402x.png)

![Logo2]
(https://www.dropbox.com/s/jad2l28p3e61ap6/Artboard%203%402x.png)

![Logo3]
(https://www.dropbox.com/s/yr10g9innvgxrte/Artboard%204%402x.png)

![Logo4]
(https://www.dropbox.com/s/x8tdd6tg80scl0h/Artboard%205%402x.png)

![Logo5]
(https://www.dropbox.com/s/jhwl6cn4d3nq45f/Artboard%206%402x.png)

![Logo6]
(https://www.dropbox.com/s/gojf2xk5c0jv5eh/Artboard%207%402x.png?dl=0)

![Logo7]
(https://www.dropbox.com/s/xq32d0qf97ov3ct/Artboard%208%402x.png?dl=0)

![Logo7]
(https://www.dropbox.com/s/xq9l9nhkxqo8efv/Artboard%209%402x.png?dl=0)

![Logo7]
(https://www.dropbox.com/s/09xe8hlmszi4ytl/Artboard%2010%402x.png?dl=0)

![Logo7]
(https://www.dropbox.com/s/z93yir0srq7amh5/Artboard%2011%402x.png?dl=0)

**Comment by sergormo** [comment]
Claro que si hombre, branding a tope, el problema de los proyectos open source es que aveces no se asocian nada mas que al código.
Lo hago por gusto. ;)

Ahi van ideas ;) 
https://www.dropbox.com/sh/r6sgg1p4pbrhbio/AACLxwzYe6NqwZp2yxCPJ7cka?dl=0

**Comment by UlisesGascon** [comment]
me gusta!!

**Comment by LeylaVieira** [comment]
Hola a todos! si aún no es muy tarde quería aportar algunas ideas en cuanto al logo 😃 
Teniendo en cuenta que el proyecto va de un calendario de eventos de tecnología he decidido tomar los clásicos símbolos del calendario, el marcador que va en el mapa y el 01 por el sistema binario (para hacer un guiño a la rama tecnológica)

![logo1_01](https://cloud.githubusercontent.com/assets/24264883/21741727/80205c52-d4df-11e6-9f8f-abb14bcfeaa8.png)

Y para esta propuesta, simplemente combinar las iniciales del nombre del proyecto más el marcador, que a su vez podría servirnos para _customizar_ el marcador de los eventos.

![logo2_02](https://cloud.githubusercontent.com/assets/24264883/21741740/dace03c0-d4df-11e6-817e-8d894b13ac32.png)

**Comment by xDae** [comment]
@LeylaVieira me gusta el segundo con las letras en el pin

**Comment by Josheriff** [comment]
Son buenísimos, enhorabuena me gustan todos, si tengo que elegir me quedo con el último. 

Un abrazo.

**Comment by UlisesGascon** [comment]
@LeylaVieira Me encanta!! El segundo es el que más me gusta :)

**Comment by sergormo** [comment]
@LeylaVieira me encanta ese background <3

Quizá lo de los números dentro del pin podría usarse no solo por el concepto de tecnología, lo del 01 lo veo muy trillado. Se podría usar el mismo svg para pasarle el dato de texto.
Que tal usarlo para poner la fecha de cada evento al estilo cards por evento?
Te cojo ese maravilloso background :)

![eventpoints](https://cloud.githubusercontent.com/assets/6580010/21744836/181803b4-d51e-11e6-8c61-9b902a0bdd17.jpg)

**Comment by UlisesGascon** [comment]
La idea de subir los archivos me gusta... que tal en /branding? Voy a daros permisos en el repo :)

**Comment by LeylaVieira** [comment]
Hi de nuevo! acabo de subir los archivos de branding para el proyecto. La tipografía que uso en la UI es la Gotham Thin, Medium y Bold, pero podemos reemplazarla por la Lato de google fonts :)

**Comment by xDae** [comment]
quizas votaria por la Lato no? (si no me equivoco la gotham es de pago)

**Comment by IgnaciodeNuevo** [comment]
La Gotham vale de 200 a 900€ la familia

**Comment by LeylaVieira** [comment]
Pues ya la he cambiado, tenéis el .psd en la carpeta UI =)
